/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import Builder.Cliente;
import Builder.ClienteBuilder;
import Builder.UsuarioDirector;
import Proxy.RepositorioUsuarios;
import Proxy.ServicioLogin;
import javax.swing.DefaultListModel;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author sete
 */
public class PantallaAltaBajaClientes extends javax.swing.JPanel {
    private PantallaApp app;
    private UsuarioDirector director;
    private ClienteBuilder clienteBuilder;
    private ServicioLogin loginService;
    private final RepositorioUsuarios repoUsuarios;
    private DefaultListModel<String> modeloClientes;
    /**
     * Creates new form AltaBajaClientes
     */
    public PantallaAltaBajaClientes(PantallaApp app,RepositorioUsuarios repoUsuarios) {
        initComponents();              
        this.app = app;
        this.repoUsuarios = repoUsuarios;

        director = new UsuarioDirector();
        clienteBuilder = new ClienteBuilder();

        
        modeloClientes = new DefaultListModel<>();
        jClientes.setModel(modeloClientes);

       
        cargarClientes();

        
        jBaja.addActionListener(e -> darDeBajaCliente());
    }
    
    private void cargarClientes() {
        modeloClientes.clear();

        // ✅ Ajusta este método según tu repo (te explico abajo)
        List<String> clientes = repoUsuarios.getUsernamesClientes();

        for (String c : clientes) {
            modeloClientes.addElement(c);
        }
    }

    private void darDeBajaCliente() {
        String seleccionado = jClientes.getSelectedValue();

        if (seleccionado == null) {
            JOptionPane.showMessageDialog(
                this,
                "Selecciona un cliente primero.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Dar de baja al cliente '" + seleccionado + "'?",
            "Confirmar baja",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (opcion != JOptionPane.YES_OPTION) return;

        try {
            // ✅ Ajusta este método según tu repo
            repoUsuarios.eliminarCliente(seleccionado);

            JOptionPane.showMessageDialog(
                this,
                "✅ Cliente dado de baja correctamente.",
                "OK",
                JOptionPane.INFORMATION_MESSAGE
            );

            // Refrescar lista
            cargarClientes();

        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(
                this,
                "❌ No se pudo dar de baja: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jClientes = new javax.swing.JList<>();
        jBaja = new javax.swing.JButton();
        lblPassword1 = new javax.swing.JLabel();
        lblPassword2 = new javax.swing.JLabel();
        jPass = new javax.swing.JPasswordField();
        txtDir = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblRegistrarse = new javax.swing.JLabel();

        setBackground(new java.awt.Color(248, 250, 252));

        jScrollPane1.setViewportView(jClientes);

        jBaja.setText("Dar de Baja");

        lblPassword1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPassword1.setText("Contraseña:");

        lblPassword2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPassword2.setText("Direccion:");

        txtDir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUser.setText("Nombre:");

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPassword.setText("Email:");

        btnRegistrarse.setBackground(new java.awt.Color(240, 245, 255));
        btnRegistrarse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegistrarse.setText("Registrar Cliente");
        btnRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseClicked(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(16, 86, 148));
        lblTitle.setText("Sistema de Gestión de Farmacias");

        lblRegistrarse.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRegistrarse.setForeground(new java.awt.Color(16, 86, 148));
        lblRegistrarse.setText("Dar de baja / Dar de alta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPassword2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPassword1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPass, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblUser)
                                    .addComponent(lblPassword))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRegistrarse)
                .addGap(160, 160, 160))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarse)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(13, 13, 13)
                .addComponent(lblRegistrarse)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUser)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword2)
                            .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword1)
                            .addComponent(jPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBaja)
                    .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseClicked
        String nombre = txtName.getText().trim();              // username
        String email = txtEmail.getText().trim();              // dato extra
        String direccion = txtDir.getText().trim();            // dato extra
        String password = new String(jPass.getPassword()).trim();

        // 1) Validación: todos rellenos
        if (nombre.isEmpty() || email.isEmpty() || direccion.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "❌ Todos los campos son obligatorios",
                "Error de registro",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        try {
            // 2) Construcción con Builder + Director
        Cliente cliente = director.constructCliente(
            clienteBuilder,
            nombre,
            email,
            password,
            direccion
        );

        // 3) Guardar en el MISMO repositorio que usa el login
        // Clave del login = nombre (username)
        repoUsuarios.registrarCliente(nombre, password, nombre);
        cargarClientes();
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "✅ Cliente registrado correctamente.\nInicia sesión con:\nUsuario: " + nombre,
            "Registro completado",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        // 4) Limpiar campos
        txtName.setText("");
        txtEmail.setText("");
        txtDir.setText("");
        jPass.setText("");

        } catch (IllegalStateException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "⚠️ Error en los datos: " + ex.getMessage(),
                "Error de validación",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        } catch (RuntimeException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "❌ No se pudo registrar: " + ex.getMessage(),
                "Error de registro",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "❌ Error inesperado al registrar",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnRegistrarseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton jBaja;
    private javax.swing.JList<String> jClientes;
    private javax.swing.JPasswordField jPass;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblPassword2;
    private javax.swing.JLabel lblRegistrarse;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
