/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 *
 * @author claud
 */
import javax.swing.JOptionPane;
public class PantallaDetallesTipo extends javax.swing.JDialog {

    private String tipo;      // "ANALGESICO"/"ANTIBIOTICO"/"ANTIINFLAMATORIO"
    private String detalle;   // nivelDolor/bacteria/zonaInflamacion

    public PantallaDetallesTipo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configurarEventos();
    }

    private void configurarEventos() {
        btnAceptar.addActionListener(e -> onAceptar());
    }
    
    public void preparar(String tipo, String valorActual) {
        this.tipo = (tipo == null) ? "" : tipo.trim().toUpperCase();
        this.detalle = null;

        // Reset
        txtBacteria.setText("");
        cmbOpciones.removeAllItems();

        // Según tipo mostramos un control u otro
        switch (this.tipo) {
            case "ANALGESICO" -> {
                lblTitle.setText("Nivel de dolor:");
                cmbOpciones.setVisible(true);
                txtBacteria.setVisible(false);

                cmbOpciones.addItem("leve");
                cmbOpciones.addItem("moderado");
                cmbOpciones.addItem("intenso");

                if (valorActual != null && !valorActual.isBlank()) {
                    cmbOpciones.setSelectedItem(valorActual.trim().toLowerCase());
                } else {
                    cmbOpciones.setSelectedIndex(0);
                }
            }
            case "ANTIINFLAMATORIO" -> {
                lblTitle.setText("Zona de inflamación:");
                cmbOpciones.setVisible(true);
                txtBacteria.setVisible(false);

                cmbOpciones.addItem("articular");
                cmbOpciones.addItem("muscular");
                cmbOpciones.addItem("general");

                if (valorActual != null && !valorActual.isBlank()) {
                    cmbOpciones.setSelectedItem(valorActual.trim().toLowerCase());
                } else {
                    cmbOpciones.setSelectedIndex(0);
                }
            }
            case "ANTIBIOTICO" -> {
                lblTitle.setText("Tipo de bacteria:");
                cmbOpciones.setVisible(false);
                txtBacteria.setVisible(true);

                if (valorActual != null) txtBacteria.setText(valorActual.trim());
            }
            default -> {
                lblTitle.setText("Detalle:");
                cmbOpciones.setVisible(false);
                txtBacteria.setVisible(false);
            }
        }

        // Refrescar
        revalidate();
        repaint();
        pack();
        setLocationRelativeTo(getParent());
    }

    private void onAceptar() {
        if (tipo == null || tipo.isBlank()) {
            JOptionPane.showMessageDialog(this, "Tipo no válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String valor;

        if (tipo.equals("ANTIBIOTICO")) {
            valor = txtBacteria.getText().trim();
            if (valor.isEmpty()) {
                JOptionPane.showMessageDialog(this, "La bacteria es obligatoria.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else {
            Object sel = cmbOpciones.getSelectedItem();
            if (sel == null) {
                JOptionPane.showMessageDialog(this, "Selecciona una opción.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            valor = sel.toString().trim().toLowerCase();
        }

        // Guardamos y cerramos
        this.detalle = valor;
        dispose();
    }

    public String getDetalle() {
        return detalle;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cmbOpciones = new javax.swing.JComboBox<>();
        txtBacteria = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(16, 86, 148));
        lblTitle.setText("Detalles del tipo de fármaco");

        cmbOpciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtBacteria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(cmbOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtBacteria, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(cmbOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(txtBacteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnAceptar)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaDetallesTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaDetallesTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaDetallesTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaDetallesTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PantallaDetallesTipo dialog = new PantallaDetallesTipo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox<String> cmbOpciones;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtBacteria;
    // End of variables declaration//GEN-END:variables
}
