/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import Builder.Cliente;
import Builder.Farmaceutico;
import Builder.FarmaceuticoBuilder;
import Builder.UsuarioDirector;
import Proxy.RepositorioUsuarios;
import Proxy.ServicioLogin;
import javax.swing.DefaultListModel;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author sete
 */
public class PantallaAltaBajaFarmaceuticos extends javax.swing.JPanel {
    private PantallaApp app;
    private UsuarioDirector director;
    private FarmaceuticoBuilder farmaceuticoBuilder;
    private ServicioLogin loginService;
    private final RepositorioUsuarios repoUsuarios;
    private DefaultListModel<String> modeloFarmaceuticos;

    public PantallaAltaBajaFarmaceuticos(PantallaApp app,RepositorioUsuarios repoUsuarios) {
        initComponents();              
        this.app = app;
        this.repoUsuarios = repoUsuarios;

        director = new UsuarioDirector();
        farmaceuticoBuilder = new FarmaceuticoBuilder();

        modeloFarmaceuticos = new DefaultListModel<>();
        jFarmaceuticos.setModel(modeloFarmaceuticos);
      
        cargarFarmaceuticos();
       
        jBaja.addActionListener(e -> darDeBajaFarmaceutico());
    }
    
    private void cargarFarmaceuticos() {
        modeloFarmaceuticos.clear();

        List<String> clientes = repoUsuarios.getUsernamesFarmaceuticos();

        for (String c : clientes) {
            modeloFarmaceuticos.addElement(c);
        }
    }

    private void darDeBajaFarmaceutico() {
        String seleccionado = jFarmaceuticos.getSelectedValue();

        if (seleccionado == null) {
            JOptionPane.showMessageDialog(
                this,
                "Selecciona un farmaceutico primero.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Dar de baja al farmaceutico '" + seleccionado + "'?",
            "Confirmar baja",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (opcion != JOptionPane.YES_OPTION) return;

        try {
            repoUsuarios.eliminarFarmaceutico(seleccionado);

            JOptionPane.showMessageDialog(
                this,
                "✅ Farmaceutico dado de baja correctamente.",
                "OK",
                JOptionPane.INFORMATION_MESSAGE
            );

            // Refrescar lista
            cargarFarmaceuticos();

        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(
                this,
                "❌ No se pudo dar de baja: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jFarmaceuticos = new javax.swing.JList<>();
        jBaja = new javax.swing.JButton();
        lblPassword1 = new javax.swing.JLabel();
        lblPassword2 = new javax.swing.JLabel();
        jPass = new javax.swing.JPasswordField();
        txtidFarmacia = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblRegistrarse = new javax.swing.JLabel();

        setBackground(new java.awt.Color(248, 250, 252));

        jScrollPane1.setViewportView(jFarmaceuticos);

        jBaja.setText("Dar de Baja");

        lblPassword1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPassword1.setText("Contraseña:");

        lblPassword2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPassword2.setText("idFarmacia:");

        txtidFarmacia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUser.setText("Nombre:");

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPassword.setText("Email:");

        btnRegistrarse.setBackground(new java.awt.Color(240, 245, 255));
        btnRegistrarse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegistrarse.setText("Registrar Farmaceutico");
        btnRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseClicked(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(16, 86, 148));
        lblTitle.setText("Sistema de Gestión de Farmacias");

        lblRegistrarse.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRegistrarse.setForeground(new java.awt.Color(16, 86, 148));
        lblRegistrarse.setText("Dar de baja / Dar de alta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPassword2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPassword1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPass, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtidFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblUser)
                                    .addComponent(lblPassword))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRegistrarse)
                .addGap(160, 160, 160))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarse)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(13, 13, 13)
                .addComponent(lblRegistrarse)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUser)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword2)
                            .addComponent(txtidFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword1)
                            .addComponent(jPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBaja)
                    .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseClicked
        String nombre = txtName.getText().trim();  
        String email = txtEmail.getText().trim();
        String idFarmacia = txtidFarmacia.getText().trim();  
        String password = new String(jPass.getPassword()).trim();

        if (nombre.isEmpty() || email.isEmpty() || idFarmacia.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "❌ Todos los campos son obligatorios",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        try {
            Farmaceutico farmaceutico = (Farmaceutico) director.constructFarmaceutico(
                farmaceuticoBuilder,
                nombre,
                email,
                password,
                idFarmacia
            );

            repoUsuarios.registrarFarmaceutico(farmaceutico);
            cargarFarmaceuticos();

            JOptionPane.showMessageDialog(
                this,
                "✅ Farmacéutico registrado correctamente",
                "Registro completado",
                JOptionPane.INFORMATION_MESSAGE
            );

            txtName.setText("");
            txtEmail.setText("");
            txtidFarmacia.setText("");
            jPass.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                this,
                ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnRegistrarseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton jBaja;
    private javax.swing.JList<String> jFarmaceuticos;
    private javax.swing.JPasswordField jPass;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblPassword2;
    private javax.swing.JLabel lblRegistrarse;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtidFarmacia;
    // End of variables declaration//GEN-END:variables
}
