/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author claud
 */
import AbstractFactory.Analgesico;
import AbstractFactory.Antibiotico;
import AbstractFactory.Antiinflamatorio;
import AbstractFactory.Medicamento;
import Bridge.AlmacenMedicamentos;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class PantallaListaFarmacos extends javax.swing.JPanel {

    private PantallaApp app;

    private DefaultListModel<String> model = new DefaultListModel<>();
    private java.util.List<Medicamento> espejo = new java.util.ArrayList<>();

    public PantallaListaFarmacos(PantallaApp app) {
        this.app = app;
        initComponents();
        configurarEventos();
        listMedicamentos.setModel(model);
    }

    private void configurarEventos() {
        btnVolver.addActionListener(e -> app.mostrarCard(PantallaApp.CARD_FARMA));

        btnModificar.addActionListener(e -> {
            if (espejo.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay medicamentos.");
                return;
            }

            int idx = listMedicamentos.getSelectedIndex();
            if (idx < 0) {
                JOptionPane.showMessageDialog(this, "Selecciona un medicamento.");
                return;
            }

            Medicamento seleccionado = espejo.get(idx);
            app.mostrarModificacionFarmacos(seleccionado);
        });
    }

    public void cargarMedicamentos() {
        model.clear();
        espejo.clear();

        var meds = AlmacenMedicamentos.getInstancia().getTodosLosMedicamentos();
        if (meds == null || meds.isEmpty()) {
            model.addElement("(No hay medicamentos)");
            listMedicamentos.setEnabled(false);
            return;
        }

        listMedicamentos.setEnabled(true);

        for (Medicamento m : meds) {
            espejo.add(m);
            model.addElement(formatearCompleto(m));
        }
    }

    /*private String formatear(Medicamento m) {
        return m.getId() + " | " + m.getNombre() + " | " + m.getTipo() + " | " + m.getFarmacia();
    }*/
    
        public static String formatearCompleto(Medicamento m) {
        if (m == null) return "(null)";
        
        DateTimeFormatter f = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        // Detalle específico según tipo
        String detalle = "";
        if (m instanceof Analgesico a) {
            detalle = "nivelDolor=" + a.getNivelDolor();
        } else if (m instanceof Antiinflamatorio ai) {
            detalle = "zonaInflamacion=" + ai.getZonaInflamacion();
        } else if (m instanceof Antibiotico ab) {
            detalle = "bacteria=" + ab.getTipoBacteria();
        } else {
            detalle = "detalle=(n/a)";
        }

        String receta = m.isRecetaMedica() ? "Sí" : "No";
        String fecha = (m.getFechaCaducidad() != null) ? m.getFechaCaducidad().format(f) : "(sin fecha)";

        return String.format(
            "ID=%s | Nombre=%s | Tipo=%s | %s | Desc=%s | Receta=%s | Precio=%.2f | Stock=%d | Cad=%s | Farmacia=%s",
            m.getId(),
            m.getNombre(),
            m.getTipo(),
            detalle,
            m.getDescripcion(),
            receta,
            m.getPrecio(),
            m.getStock(),
            fecha,
            m.getFarmacia()
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMedicamentos = new javax.swing.JList<>();
        btnModificar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(16, 86, 148));
        lblTitle.setText("Lista de fármacos");

        listMedicamentos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(listMedicamentos);

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");

        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVolver.setText("Volver al menú");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnVolver)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnVolver))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> listMedicamentos;
    // End of variables declaration//GEN-END:variables
}
