/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Builder.Cliente;
import Builder.ClienteBuilder;
import Builder.UsuarioDirector;
import Proxy.RepositorioUsuarios;
import Proxy.ServicioLogin;

/**
 *
 * @author claud
 */
public class PantallaRegistroCliente extends javax.swing.JPanel {
    private PantallaApp app;
    private UsuarioDirector director;
    private ClienteBuilder clienteBuilder;
    private ServicioLogin loginService;
    private final RepositorioUsuarios repoUsuarios;
    
    public PantallaRegistroCliente(PantallaApp app,RepositorioUsuarios repoUsuarios) {
        initComponents();
        this.app = app;
        director = new UsuarioDirector();
        clienteBuilder = new ClienteBuilder();
        this.repoUsuarios = repoUsuarios;
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblRegistrarse = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblPassword1 = new javax.swing.JLabel();
        lblPassword2 = new javax.swing.JLabel();
        jPass = new javax.swing.JPasswordField();
        txtDir = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();

        setBackground(new java.awt.Color(248, 250, 252));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(16, 86, 148));
        lblTitle.setText("Sistema de Gestión de Farmacias");

        lblRegistrarse.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRegistrarse.setForeground(new java.awt.Color(16, 86, 148));
        lblRegistrarse.setText("Registrarse");

        btnRegistrarse.setBackground(new java.awt.Color(240, 245, 255));
        btnRegistrarse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseClicked(evt);
            }
        });

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUser.setText("Nombre:");

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPassword.setText("Email:");

        lblPassword1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPassword1.setText("Contraseña:");

        lblPassword2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPassword2.setText("Direccion:");

        txtDir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(lblRegistrarse))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(btnRegistrarse))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPassword2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPassword1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPass, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblUser)
                                    .addComponent(lblPassword))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(txtEmail))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRegistrarse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword2)
                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword1)
                    .addComponent(jPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(btnRegistrarse)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseClicked
        String nombre = txtName.getText().trim();              // username
        String email = txtEmail.getText().trim();              // dato extra
        String direccion = txtDir.getText().trim();            // dato extra
        String password = new String(jPass.getPassword()).trim();

        // 1) Validación: todos rellenos
        if (nombre.isEmpty() || email.isEmpty() || direccion.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "❌ Todos los campos son obligatorios",
                    "Error de registro",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        try {
            // 2) Construcción con Builder + Director
            Cliente cliente = director.constructCliente(
                    clienteBuilder,
                    nombre,
                    email,
                    password,
                    direccion
            );
            
            repoUsuarios.registrarCliente(cliente);

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "✅ Cliente registrado correctamente.\nInicia sesión con:\nUsuario: " + nombre,
                    "Registro completado",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            // 4) Limpiar campos
            txtName.setText("");
            txtDir.setText("");
            txtDir.setText("");
            jPass.setText("");

            // 5) Volver a login (si tu PantallaApp tiene un método para ello)
            // Cambia el nombre del método según tu PantallaApp:
            app.mostrarLoginConRol("CLIENTE"); 
            // o: app.mostrarLogin(); y luego app.getPantallaLogin().setRolSeleccionado("CLIENTE");

        } catch (IllegalStateException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "⚠️ Error en los datos: " + ex.getMessage(),
                    "Error de validación",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        } catch (RuntimeException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "❌ No se pudo registrar: " + ex.getMessage(),
                    "Error de registro",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "❌ Error inesperado al registrar",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnRegistrarseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JPasswordField jPass;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblPassword2;
    private javax.swing.JLabel lblRegistrarse;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
