/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author claud
 */
import Proxy.Sesion;
public class PantallaFarmaceutico extends javax.swing.JPanel {

    private PantallaApp app;

    public PantallaFarmaceutico(PantallaApp app) {
        this.app = app;
        initComponents();
        configurarEventos();
    }

    private void configurarEventos() {
        btnLogout.addActionListener(e -> app.mostrarRol());
        btnBuscarFarmacos.addActionListener(e -> app.mostrarBuscarFarmacos(PantallaApp.CARD_FARMA));
        btnAltaBajaFarmacos.addActionListener(e -> app.mostrarAltaBajaFarmacos());
        btnModificacionFarmacos.addActionListener(e -> app.mostrarListaFarmacos());
    }

    public void setSesion(Sesion sesion) {
        lblInfo.setText("Farmacéutico: " + sesion.getNombre() +
                " | ID: " + sesion.getIdUsuario() +
                " | Rol: " + sesion.getRol());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnAltaBajaFarmacos = new javax.swing.JButton();
        btnBuscarFarmacos = new javax.swing.JButton();
        btnModificacionFarmacos = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(16, 86, 148));
        lblTitle.setText("Panel farmacéutico");

        lblInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogout.setText("Cerrar sesión");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnAltaBajaFarmacos.setBackground(new java.awt.Color(240, 245, 255));
        btnAltaBajaFarmacos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAltaBajaFarmacos.setText("Alta/Baja de fármacos");
        btnAltaBajaFarmacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaBajaFarmacosActionPerformed(evt);
            }
        });

        btnBuscarFarmacos.setBackground(new java.awt.Color(240, 245, 255));
        btnBuscarFarmacos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscarFarmacos.setText("Buscar fármacos");
        btnBuscarFarmacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFarmacosActionPerformed(evt);
            }
        });

        btnModificacionFarmacos.setBackground(new java.awt.Color(240, 245, 255));
        btnModificacionFarmacos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificacionFarmacos.setText("Modificación de fármacos");
        btnModificacionFarmacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificacionFarmacosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                            .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAltaBajaFarmacos, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnBuscarFarmacos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnModificacionFarmacos))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btnLogout)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarFarmacos)
                .addGap(33, 33, 33)
                .addComponent(btnModificacionFarmacos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnAltaBajaFarmacos)
                .addGap(38, 38, 38)
                .addComponent(btnLogout)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBuscarFarmacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFarmacosActionPerformed


    }//GEN-LAST:event_btnBuscarFarmacosActionPerformed

    private void btnAltaBajaFarmacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaBajaFarmacosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltaBajaFarmacosActionPerformed

    private void btnModificacionFarmacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificacionFarmacosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificacionFarmacosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaBajaFarmacos;
    private javax.swing.JButton btnBuscarFarmacos;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnModificacionFarmacos;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
