/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author claud
 */
import AbstractFactory.Analgesico;
import AbstractFactory.Antibiotico;
import AbstractFactory.Antiinflamatorio;
import AbstractFactory.Medicamento;
import Bridge.AlmacenMedicamentos;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class PantallaBajaFarmacos extends javax.swing.JPanel {

    private PantallaApp app;

    private DefaultListModel<String> model = new DefaultListModel<>();
    private java.util.List<Medicamento> espejo = new java.util.ArrayList<>();

    public PantallaBajaFarmacos(PantallaApp app) {
        this.app = app;
        initComponents();
        configurarEventos();

        // Vincular modelo al JList
        listMedicamentos.setModel(model);
    }

    private void configurarEventos() {
        btnVolver.addActionListener(e -> app.mostrarCard(PantallaApp.CARD_ALTA_BAJA));
        btnBaja.addActionListener(e -> darDeBajaSeleccionado());
    }

    public void cargarMedicamentos() {
        model.clear();
        espejo.clear();

        var meds = AlmacenMedicamentos.getInstancia().getTodosLosMedicamentos();

        if (meds == null || meds.isEmpty()) {
            model.addElement("(No hay medicamentos)");
            listMedicamentos.setEnabled(false);
            return;
        }

        listMedicamentos.setEnabled(true);

        for (Medicamento m : meds) {
            espejo.add(m);
            model.addElement(formatearCompleto(m));
        }
    }

    private void darDeBajaSeleccionado() {
        if (espejo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay medicamentos para dar de baja.");
            return;
        }

        int idx = listMedicamentos.getSelectedIndex();
        if (idx < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un medicamento de la lista.");
            return;
        }

        Medicamento seleccionado = espejo.get(idx);

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres dar de baja:\n" + formatearCompleto(seleccionado) + "?",
                "Confirmar baja",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) return;

        boolean ok = AlmacenMedicamentos.getInstancia().eliminarMedicamento(seleccionado);

        if (!ok) {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar (puede que ya no exista).");
        } else {
            JOptionPane.showMessageDialog(this, "Medicamento dado de baja correctamente.");
        }

        // refrescar lista
        cargarMedicamentos();
    }
    
    public static String formatearCompleto(Medicamento m) {
        if (m == null) return "(null)";
        
        DateTimeFormatter f = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        // Detalle específico según tipo
        String detalle = "";
        if (m instanceof Analgesico a) {
            detalle = "nivelDolor=" + a.getNivelDolor();
        } else if (m instanceof Antiinflamatorio ai) {
            detalle = "zonaInflamacion=" + ai.getZonaInflamacion();
        } else if (m instanceof Antibiotico ab) {
            detalle = "bacteria=" + ab.getTipoBacteria();
        } else {
            detalle = "detalle=(n/a)";
        }

        String receta = m.isRecetaMedica() ? "Sí" : "No";
        String fecha = (m.getFechaCaducidad() != null) ? m.getFechaCaducidad().format(f) : "(sin fecha)";

        return String.format(
            "ID=%s | Nombre=%s | Tipo=%s | %s | Desc=%s | Receta=%s | Precio=%.2f | Stock=%d | Cad=%s | Farmacia=%s",
            m.getId(),
            m.getNombre(),
            m.getTipo(),
            detalle,
            m.getDescripcion(),
            receta,
            m.getPrecio(),
            m.getStock(),
            fecha,
            m.getFarmacia()
        );
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnBaja = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMedicamentos = new javax.swing.JList<>();
        btnVolver = new javax.swing.JButton();

        setBackground(new java.awt.Color(248, 250, 252));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(16, 86, 148));
        lblTitle.setText("Baja de fármacos");

        btnBaja.setBackground(new java.awt.Color(240, 245, 255));
        btnBaja.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBaja.setText("Dar de baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listMedicamentos);

        btnVolver.setBackground(new java.awt.Color(240, 245, 255));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVolver.setText("Atrás");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(btnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaja)
                    .addComponent(btnVolver))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBajaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> listMedicamentos;
    // End of variables declaration//GEN-END:variables
}
