/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Proxy.*;
import java.awt.CardLayout;

/**
 *
 * @author claud
 */
public class PantallaApp extends javax.swing.JFrame {
    // CardLayout
    private CardLayout cardLayout;

    // Proxy login
    private ServicioLogin loginService;

    // Panels
    private PantallaLogin pantallaLogin;
    private PantallaCliente pantallaCliente;
    private PantallaFarmaceutico pantallaFarmaceutico;
    private PantallaAdmin pantallaAdmin;

    // Nombres de cartas
    public static final String CARD_LOGIN = "LOGIN";
    public static final String CARD_CLIENTE = "CLIENTE";
    public static final String CARD_FARMA = "FARMA";
    public static final String CARD_ADMIN = "ADMIN";

    /**
     * Creates new form PantallaApp
     */
    public PantallaApp() {
        initComponents();
        initApp();
    }

    private void initApp() {
        // 1) Crear servicio real + proxy
        RepositorioUsuarios repo = new RepositorioUsuarios();
        ServicioLogin real = new ServicioLoginReal(repo);
        loginService = new ServicioLoginProxy(real);

        // 2) CardLayout del contentPanel (ya lo pusiste en el diseñador)
        cardLayout = (CardLayout) contentPanel.getLayout();

        // 3) Crear pantallas
        pantallaLogin = new PantallaLogin(this, loginService);
        pantallaCliente = new PantallaCliente(this);
        pantallaFarmaceutico = new PantallaFarmaceutico(this);
        pantallaAdmin = new PantallaAdmin(this);

        // 4) Añadir al CardLayout
        contentPanel.add(pantallaLogin, CARD_LOGIN);
        contentPanel.add(pantallaCliente, CARD_CLIENTE);
        contentPanel.add(pantallaFarmaceutico, CARD_FARMA);
        contentPanel.add(pantallaAdmin, CARD_ADMIN);

        // 5) Mostrar login
        mostrarLogin();
    }

    public void mostrarLogin() {
        pantallaLogin.resetFields();
        cardLayout.show(contentPanel, CARD_LOGIN);
    }

    public void mostrarCliente(Sesion sesion) {
        pantallaCliente.setSesion(sesion);
        cardLayout.show(contentPanel, CARD_CLIENTE);
    }

    public void mostrarFarmaceutico(Sesion sesion) {
        pantallaFarmaceutico.setSesion(sesion);
        cardLayout.show(contentPanel, CARD_FARMA);
    }

    public void mostrarAdmin(Sesion sesion) {
        pantallaAdmin.setSesion(sesion);
        cardLayout.show(contentPanel, CARD_ADMIN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    // End of variables declaration//GEN-END:variables
}
